"""add service id to appointment

Revision ID: 2133b69d0ae8
Revises: 34b4ebc1acbb
Create Date: 2026-07-03 11:41:29.321925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2133b69d0ae8'
down_revision: Union[str, Sequence[str], None] = '34b4ebc1acbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('service_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_appointment_service_id_service', 'appointment', 'service', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_appointment_service_id_service', 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'service_id')
    # ### end Alembic commands ###
