"""add provider id to appointment

Revision ID: 34b4ebc1acbb
Revises: bfe7e869c736
Create Date: 2026-07-03 09:42:54.093610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b4ebc1acbb'
down_revision: Union[str, Sequence[str], None] = 'bfe7e869c736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('provider_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_appointment_provider_id_provider', 'appointment', 'provider', ['provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_appointment_provider_id_provider', 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'provider_id')
    # ### end Alembic commands ###
