"""add role to user and link provider to user

Revision ID: 7d2ec84c8af0
Revises: 2133b69d0ae8
Create Date: 2026-07-06 13:17:16.690843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7d2ec84c8af0'
down_revision: Union[str, Sequence[str], None] = '2133b69d0ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'provider', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_constraint(None, 'provider', type_='foreignkey')
    op.drop_column('provider', 'user_id')
    # ### end Alembic commands ###
